services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: angular_nginx_second:latest
    ports:
      - "9393:80"
    environment:
      - NODE_ENV=production
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
